import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useSelector, useDispatch } from 'react-redux';
import { increment, decrement } from '../redux/actions';
import Link from 'next/link';

export default function Home() {
    const count = useSelector((state) => state.counter);
    const dispatch = useDispatch();

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <Link href="/pdf-viewer">View Pdf</Link>
                <h1> Counter</h1>
                <h2>{count}</h2>
                <div className="btn-group">
                    <button
                        className="btn btn-primary"
                        onClick={() => dispatch(increment())}
                    >
                        +
                    </button>
                    <button
                        className="btn btn-primary"
                        onClick={() => dispatch(decrement())}
                    >
                        -
                    </button>
                </div>
            </div>
        </div>
    );
}
