import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useSelector, useDispatch } from "react-redux";
import { increment, decrement } from "../redux/actions";

export default function Home() {
    const count = useSelector((state) => state.counter);
    const dispatch = useDispatch();

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <h1> Counter</h1>
                <h2>{count}</h2>
                <div>
                    <button onClick={() => dispatch(increment())}>+</button>
                    <button onClick={() => dispatch(decrement())}>-</button>
                </div>
            </div>
        </div>
    );
}
